/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: LocalizedText;
  author?: LocalizedString;
  detail?: LocalizedString;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sourceUrl?: string;
  order?: number;
  isVisible?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type LocalizedString = {
  _type: "localizedString";
  ru?: string;
  en?: string;
};

export type LocalizedText = {
  _type: "localizedText";
  ru?: string;
  en?: string;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  aboutText?: LocalizedText;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  skills?: Array<
    {
      _key: string;
    } & ProfileItem
  >;
  tools?: Array<
    {
      _key: string;
    } & ProfileItem
  >;
  platforms?: Array<
    {
      _key: string;
    } & ProfileItem
  >;
};

export type ShortVideo = {
  _id: string;
  _type: "shortVideo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  description?: LocalizedText;
  youtubeUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: "shorts" | "reels";
  order?: number;
  isVisible?: boolean;
};

export type VideoProject = {
  _id: string;
  _type: "videoProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  description?: LocalizedText;
  youtubeUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: "youtube" | "commercial" | "podcast";
  order?: number;
  isVisible?: boolean;
};

export type Showreel = {
  _id: string;
  _type: "showreel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  description?: LocalizedText;
  youtubeUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  isVisible?: boolean;
};

export type ProfileItem = {
  _type: "profileItem";
  name?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Review
  | SanityImageCrop
  | SanityImageHotspot
  | LocalizedString
  | LocalizedText
  | Profile
  | ShortVideo
  | VideoProject
  | Showreel
  | ProfileItem
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../site/src/sanity/queries.ts
// Variable: SITE_CONTENT_QUERY
// Query: {  "showreel": *[_id == "showreel" && _type == "showreel"][0]{    _id,    title,    description,    youtubeUrl,    poster,    isVisible  },  "works": *[_type == "videoProject" && isVisible != false] | order(order asc, _createdAt asc){    _id,    title,    description,    youtubeUrl,    poster,    category  },  "shorts": *[_type == "shortVideo" && isVisible != false] | order(order asc, _createdAt asc){    _id,    title,    description,    youtubeUrl,    poster,    category  },  "profile": *[_id == "profile" && _type == "profile"][0]{    aboutText,    portrait,    skills[]{_key, name, icon},    tools[]{_key, name, icon},    platforms[]{_key, name, icon}  },  "reviews": *[_type == "review" && isVisible != false] | order(order asc, _createdAt asc){    _id,    quote,    author,    detail,    avatar,    sourceUrl  }}
export type SITE_CONTENT_QUERY_RESULT = {
  showreel: {
    _id: "showreel";
    title: LocalizedString | null;
    description: LocalizedText | null;
    youtubeUrl: string | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    isVisible: boolean | null;
  } | null;
  works: Array<{
    _id: string;
    title: LocalizedString | null;
    description: LocalizedText | null;
    youtubeUrl: string | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    category: "commercial" | "podcast" | "youtube" | null;
  }>;
  shorts: Array<{
    _id: string;
    title: LocalizedString | null;
    description: LocalizedText | null;
    youtubeUrl: string | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    category: "reels" | "shorts" | null;
  }>;
  profile: {
    aboutText: LocalizedText | null;
    portrait: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    skills: Array<{
      _key: string;
      name: string | null;
      icon: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
    tools: Array<{
      _key: string;
      name: string | null;
      icon: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
    platforms: Array<{
      _key: string;
      name: string | null;
      icon: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  } | null;
  reviews: Array<{
    _id: string;
    quote: LocalizedText | null;
    author: LocalizedString | null;
    detail: LocalizedString | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    sourceUrl: string | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "showreel": *[_id == "showreel" && _type == "showreel"][0]{\n    _id,\n    title,\n    description,\n    youtubeUrl,\n    poster,\n    isVisible\n  },\n  "works": *[_type == "videoProject" && isVisible != false] | order(order asc, _createdAt asc){\n    _id,\n    title,\n    description,\n    youtubeUrl,\n    poster,\n    category\n  },\n  "shorts": *[_type == "shortVideo" && isVisible != false] | order(order asc, _createdAt asc){\n    _id,\n    title,\n    description,\n    youtubeUrl,\n    poster,\n    category\n  },\n  "profile": *[_id == "profile" && _type == "profile"][0]{\n    aboutText,\n    portrait,\n    skills[]{_key, name, icon},\n    tools[]{_key, name, icon},\n    platforms[]{_key, name, icon}\n  },\n  "reviews": *[_type == "review" && isVisible != false] | order(order asc, _createdAt asc){\n    _id,\n    quote,\n    author,\n    detail,\n    avatar,\n    sourceUrl\n  }\n}': SITE_CONTENT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
